run_root: 'run'
data_root: 'run/single_person'
checkpoint_root: 'run/checkpoints'

# dataset build
person_margin_ratio: !!float 0.1

# resume stuff
resume: !!bool False
resume_id: 1

input_h: !!int 288
input_w: !!int 384

epochs: 200
batch_size: 128
learning_rate: !!float 4e-3

# optimizer and scheduler
div_factor: !!float 25.0
warmup_pct: !!float 0.01

n_viz: 3

num_workers_train: 12
num_workers_val: 8
pin_memory: !!bool True
prefetch_factor: 4



