run_root: 'run'
data_root: 'run/single_person'
checkpoint_root: 'run/checkpoints'

# dataset build
person_margin_ratio: !!float 0.1

bins: 4

# resume stuff
resume: !!bool False
resume_id: 1

input_h: !!int 384
input_w: !!int 384

epochs: 200
batch_size: 64 # 256
learning_rate: !!float 2.5e-4 # 1e-3

# optimizer and scheduler
div_factor: !!float 25.0
warmup_pct: !!float 0.1

weight_warm_pct: 10

max_samples_train: 256 # None
max_samples_val: 16 # None

n_viz: 3

num_workers_train: 24
num_workers_val: 16
pin_memory: !!bool True
prefetch_factor: 4



