data_root: 'run/data'
batch_size: 64
learning_rate: !!float 1e-4
epochs: 1000
img_h: 256
img_w: 256
hm_h: 128
hm_w: 128
sigma: 2
ohkm_k: 8
n_vis: 6
num_workers_train: 16
num_workers_val: 8
grad_clip: 5.0
seed: 42
use_amp: True
use_ema: True
struct_weight: 0.0


