run_root: 'run'
data_root: 'run/single_person'
checkpoint_root: 'run/checkpoints'

data_root_val: 'run/data/'
ann_file_val: 'annotations/person_keypoints_val2017.json'

# dataset build
person_margin_ratio: !!float 0.1

bins: 4

# resume stuff
resume: !!bool False
resume_id: 1

input_size: !!int 384

epochs: 200
batch_size: 512
learning_rate: !!float 5e-3

# optimizer and scheduler
div_factor: !!float 25.0
warmup_pct: !!float 0.1

weight_warm_pct: 10

max_samples_train: 1024
max_samples_val: 64

n_viz: 3

num_workers_train: 24
num_workers_val: 24
batch_size_val: 1

pin_memory: !!bool True
prefetch_factor: 4

wandb: online