name: Build & Publish Docker image

# 触发条件：当代码 push 或 PR 到 master 分支时执行
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-publish:
    name: Build & Publish Docker Image
    runs-on: ubuntu-latest
    # 为了推送到 GHCR，内容权限需要 write
    permissions:
      contents: read    # 读取代码
      packages: write   # 推送到 GitHub Container Registry

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 可选：让 Buildx 支持多架构构建
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          # 如果不需要多架构，可以删除或注释掉 platforms
          # platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/ruihanzhao/joint_angle:latest
            ghcr.io/ruihanzhao/joint_angle:${{ github.sha }}

